export const SET_USER = 'SET_USER';
export const SET_SEARCH_TERM = 'SET_USER_SEARCH_TERM';
export const SET_MOBILE_MENU_VISIBILITY = 'SET_MOBILE_MENU_VISIBILITY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_QUERY = 'SET_QUERY';
